version: 1

formatters:
    standard:
        format: '%(asctime)s - %(levelname)s - %(module)s.%(funcName)s(): %(lineno)d: %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    file:
        # `filename` will be set by `telog.py` to ensure that the log files always stay somewhere in the dir
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, file]